### ISSUE TITLE
Java frontend (console)

### ISSUE THREAD

**Issue by KIMB0** [AlexanderFalk/rapp#5]
### Description
This is a simple Java console frontend, where a user can put in:
- SSN
- Loan Amount
- Loan Duration

### Tasks
- [ ] Create new class
- [ ] Create user input
### Acceptance criterias
- [ ] I can/cannot [do something]

### Definition of Done
- [ ] Tested
- [ ] Reviewed
